name: Pipeline CD: Despliegue Frontend (GitHub Pages)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Instalar dependencias
      run: npm install --legacy-peer-deps

    - name: Compilar aplicación de Angular
      # Configuramos la base-href para GitHub Pages (opcionalmente puedes añadir --base-href /repo/)
      run: npm run build -- --configuration production

    - name: Desplegar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # La salida del build de Angular en esta versión específica está en dist/frontend
        publish_dir: ./frontend/dist/frontend
