name: CD Frontend (GitHub Pages)

on:
  push:
    branches: [ "main" ] # Se activa tras hacer push o mergear a main

# Permisos necesarios para que GitHub Actions pueda publicar en la rama gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Instalar dependencias
      run: npm install

    - name: Compilar aplicación de Angular para Producción
      # Asegúrate de configurar la base-href si tu repositorio no es la raíz del dominio
      # Ejemplo: --base-href /nombre-del-repo/
      run: npm run build -- --configuration production

    - name: Desplegar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Cambia 'frontend' por el nombre de tu proyecto Angular que se genera dentro de dist/
        publish_dir: ./frontend/dist/frontend
        commit_message: "🚀 Despliegue automático a GitHub Pages"
