name: CI Frontend (Angular)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Instalar dependencias
      # Usamos legacy-peer-deps para evitar conflictos de librerías en Angular v17+
      run: npm install --legacy-peer-deps

    - name: Compilar aplicación (Build)
      run: npm run build
